# Generated by Django 3.1.3 on 2020-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="uploaded",
            field=models.BooleanField(default=False),
        ),
    ]
