# Generated by Django 3.1.3 on 2020-11-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lines", "0002_line_uploaded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="script",
            name="writer",
        ),
    ]
